"""3-D export: point clouds and oriented boxes to PLY/OBJ.

Being able to open the reconstruction in MeshLab or CloudCompare is the fastest
way to diagnose a suspicious measurement -- depth bleed, a mis-fitted support
plane and a leaking mask all look obviously wrong in 3-D and completely normal
in a JSON payload.

Binary PLY is written rather than ASCII: point clouds run to millions of
points, where ASCII is roughly 4x larger and far slower to parse.
"""

from __future__ import annotations

import struct
from pathlib import Path
from typing import Any

import numpy as np
from numpy.typing import NDArray

from measurecv.core.types import Dimensions, PointCloud

__all__ = ["write_obb_obj", "write_ply"]


def write_ply(
    path: str | Path,
    cloud: PointCloud,
    *,
    binary: bool = True,
    normals: NDArray[np.float64] | None = None,
) -> Path:
    """Write a point cloud to PLY.

    Args:
        path: Destination.
        cloud: Points, optionally coloured.
        binary: Binary little-endian (default) or ASCII.
        normals: Optional ``(N, 3)`` per-point normals.

    Returns:
        The written path.
    """
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)

    points = np.asarray(cloud.points, dtype=np.float32)
    n = points.shape[0]
    colors = cloud.colors
    has_color = colors is not None and len(colors) == n
    has_normals = normals is not None and len(normals) == n

    header = [
        "ply",
        f"format {'binary_little_endian' if binary else 'ascii'} 1.0",
        "comment generated by measurecv",
        f"element vertex {n}",
        "property float x",
        "property float y",
        "property float z",
    ]
    if has_normals:
        header += ["property float nx", "property float ny", "property float nz"]
    if has_color:
        header += ["property uchar red", "property uchar green", "property uchar blue"]
    header.append("end_header")
    header_bytes = ("\n".join(header) + "\n").encode("ascii")

    if binary:
        fields: list[NDArray[Any]] = [points]
        dtype: list[tuple[str, str]] = [("x", "<f4"), ("y", "<f4"), ("z", "<f4")]
        if has_normals:
            fields.append(np.asarray(normals, dtype=np.float32))
            dtype += [("nx", "<f4"), ("ny", "<f4"), ("nz", "<f4")]
        if has_color:
            fields.append(np.asarray(colors, dtype=np.uint8))
            dtype += [("red", "u1"), ("green", "u1"), ("blue", "u1")]

        record = np.empty(n, dtype=dtype)
        offset = 0
        for block in fields:
            width = block.shape[1]
            for column in range(width):
                record[dtype[offset + column][0]] = block[:, column]
            offset += width

        with out.open("wb") as handle:
            handle.write(header_bytes)
            handle.write(record.tobytes())
    else:
        lines = [header_bytes.decode("ascii")]
        for i in range(n):
            parts = [f"{points[i, 0]:.6f}", f"{points[i, 1]:.6f}", f"{points[i, 2]:.6f}"]
            if has_normals:
                parts += [f"{v:.6f}" for v in normals[i]]  # type: ignore[index]
            if has_color:
                parts += [str(int(v)) for v in colors[i]]  # type: ignore[index]
            lines.append(" ".join(parts))
        out.write_text("\n".join(lines) + "\n", encoding="ascii")

    return out


def write_obb_obj(
    path: str | Path, boxes: list[Dimensions], *, labels: list[str] | None = None
) -> Path:
    """Write oriented bounding boxes as an OBJ wireframe.

    Each box becomes a named group so a viewer can toggle objects individually.
    """
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)

    signs = np.array(
        [[sx, sy, sz] for sx in (-1, 1) for sy in (-1, 1) for sz in (-1, 1)], dtype=np.float64
    )
    edges = [
        (0, 1),
        (0, 2),
        (0, 4),
        (1, 3),
        (1, 5),
        (2, 3),
        (2, 6),
        (3, 7),
        (4, 5),
        (4, 6),
        (5, 7),
        (6, 7),
    ]

    lines: list[str] = ["# measurecv oriented bounding boxes", "# units: metres"]
    vertex_offset = 1  # OBJ indices are 1-based

    for i, dims in enumerate(boxes):
        if dims.axes is None or dims.origin is None:
            continue
        name = labels[i] if labels and i < len(labels) else f"object_{i}"
        extents = np.array([dims.length.value, dims.width.value, dims.height.value])
        corners = dims.origin + (signs * extents * 0.5) @ dims.axes

        lines.append(f"g {name}")
        for corner in corners:
            lines.append(f"v {corner[0]:.6f} {corner[1]:.6f} {corner[2]:.6f}")
        for a, b in edges:
            lines.append(f"l {vertex_offset + a} {vertex_offset + b}")
        vertex_offset += 8

    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out


def read_ply_header(path: str | Path) -> dict[str, Any]:
    """Parse a PLY header. Used by tests to verify round-tripping."""
    info: dict[str, Any] = {"properties": [], "count": 0, "format": ""}
    with Path(path).open("rb") as handle:
        while True:
            raw = handle.readline()
            if not raw:
                break
            line = raw.decode("ascii", errors="replace").strip()
            if line.startswith("format"):
                info["format"] = line.split()[1]
            elif line.startswith("element vertex"):
                info["count"] = int(line.split()[2])
            elif line.startswith("property"):
                info["properties"].append(line.split()[-1])
            elif line == "end_header":
                info["header_bytes"] = handle.tell()
                break
    return info


def _pack_vertex(x: float, y: float, z: float) -> bytes:  # pragma: no cover - reference helper
    return struct.pack("<fff", x, y, z)
