#!/usr/bin/env python
"""
Reset the demo database to a clean, presentable state.

Run this before a demo or a recording. Testing writes real rows — every FAIL
verdict creates a real FieldIssue — so after a few verification passes the
dashboard shows a pile of duplicate CRITICAL "spacing_deviation" entries that
are test artifacts, not the curated demo scenario a judge should see.

    python scripts/reset_demo_data.py            # show what would be removed
    python scripts/reset_demo_data.py --apply    # actually remove it
    python scripts/reset_demo_data.py --apply --all   # also clear interactions

What it removes (test artifacts only):
  · FieldIssue rows whose issue_type was generated by the compliance agent
    ("<parameter>_deviation") — the seeded demo issues use human labels like
    "Rebar Grid" and "Conduit Routing", so they are never touched
  · the ComplianceEvent rows linked to those
  · anything tagged with the verification zone/worker
  · with --all, the interaction history as well

What it never touches: the five seeded demo issues, the three zones, users,
drawings, or resolved incidents. Deletion is scoped by an explicit allow-list,
not by "delete everything recent".
"""

from __future__ import annotations

import argparse
import asyncio
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(REPO / "api"))

VERIFY_ZONE = "ZZ-VERIFY"
VERIFY_WORKER = "W-VERIFY"

# Issue types the compliance agent generates automatically. Seeded demo issues
# use prose labels ("Rebar Grid"), so this can't collide with them.
GENERATED_SUFFIX = "_deviation"


async def run(apply: bool, include_interactions: bool) -> int:
    from db import async_session
    from models.compliance import ComplianceEvent
    from models.interaction import Interaction
    from models.issues import FieldIssue
    from sqlalchemy import delete, or_, select

    async with async_session() as s:
        issues = (await s.execute(select(FieldIssue))).scalars().all()
        doomed = [i for i in issues
                  if (i.issue_type or "").endswith(GENERATED_SUFFIX)
                  or i.zone_code == VERIFY_ZONE
                  or i.worker_id == VERIFY_WORKER]
        keepers = [i for i in issues if i not in doomed]

        print(f"\n  field_issues: {len(issues)} total")
        print(f"    to remove : {len(doomed)}")
        for i in doomed[:12]:
            print(f"        {(i.issue_type or '?'):<24} zone {(i.zone_code or '?'):<8} "
                  f"{(i.severity or '?')}")
        if len(doomed) > 12:
            print(f"        … and {len(doomed) - 12} more")
        print(f"    to keep   : {len(keepers)}")
        for i in keepers:
            print(f"        {(i.issue_type or '?'):<24} zone {(i.zone_code or '?'):<8} "
                  f"{(i.severity or '?')}")

        interactions = (await s.execute(select(Interaction))).scalars().all()
        if include_interactions:
            int_doomed = interactions
        else:
            int_doomed = [x for x in interactions
                          if x.zone_code == VERIFY_ZONE or x.worker_id == VERIFY_WORKER]
        print(f"\n  interactions: {len(interactions)} total, "
              f"{len(int_doomed)} to remove"
              + ("" if include_interactions else "  (use --all to clear the whole feed)"))

        if not apply:
            print("\n  DRY RUN — nothing changed. Re-run with --apply to remove.")
            return 0

        doomed_ids = [i.id for i in doomed]
        if doomed_ids:
            await s.execute(delete(ComplianceEvent).where(
                ComplianceEvent.field_issue_id.in_(doomed_ids)))
            await s.execute(delete(FieldIssue).where(FieldIssue.id.in_(doomed_ids)))
        await s.execute(delete(ComplianceEvent).where(
            ComplianceEvent.zone_code == VERIFY_ZONE))

        if include_interactions:
            await s.execute(delete(Interaction))
        else:
            await s.execute(delete(Interaction).where(
                or_(Interaction.zone_code == VERIFY_ZONE,
                    Interaction.worker_id == VERIFY_WORKER)))

        await s.commit()
        print(f"\n  Removed {len(doomed_ids)} issues and {len(int_doomed)} interactions.")

    # Zone counters are recomputed by the scoring task, but it runs on a timer;
    # bring them in line now so the dashboard is correct immediately.
    async with async_session() as s:
        from models.zones import Zone
        zones = (await s.execute(select(Zone))).scalars().all()
        remaining = (await s.execute(select(FieldIssue))).scalars().all()
        for z in zones:
            open_count = sum(1 for i in remaining
                             if i.zone_code == z.zone_code and (i.status or "open") == "open")
            z.open_issue_count = open_count
        await s.commit()
        print("  Recomputed zone open-issue counts: "
              + ", ".join(f"{z.zone_code}={z.open_issue_count}" for z in zones))

    print("\n  Dashboard is back to the curated demo scenario.")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--apply", action="store_true", help="actually delete (default: dry run)")
    ap.add_argument("--all", action="store_true", dest="all_interactions",
                    help="also clear the entire interaction history feed")
    args = ap.parse_args()
    return asyncio.run(run(args.apply, args.all_interactions))


if __name__ == "__main__":
    raise SystemExit(main())
